host: host
port: 3306
database: database
playersBankTable: PlayersBank
entBankTable: EntBank
tombolaTable: Tombola
tombolaWinTable: TombolaWin
login: login
password: password
mainColor: GOLD
errorColor: RED
moneySymbol: £
tombolaPrice: 50