host: host
port: 3306
database: database
playersBankTable: PlayersBank
entBankTable: EntBank
tombolaTable: Tombola
tombolaWinTable: TombolaWin
login: login
password: password
mainColor: GOLD
errorColor: RED
moneySymbol: £
tombolaPrice: 50
accessErrorMessage: "Vous n'avez pas accès à cette commande."
amountErrorMessage: "Le montant doit être un nombre."
playerErrorMessage: "Ce joueur n'est pas connecté."