name: EconomyAPI
version: 0.2b2
author: Paragoumba
authors: [Foxxen]
main: fr.paragoumba.minediversity.economyapi.EconomyAPI
commands:
  tombola:
    description: Bonjour
  money:
    description: Hello
  event:
    description: Hola