name: EconomyAPI
version: 1.4b19
author: Paragoumba
authors: [MrCapi]
main: fr.paragoumba.minediversity.economyapi.EconomyAPI
commands:
  tombola:
    description: Command to interact with the tombola.
    usage: /tombola [play]
  money:
    description: Reloads the plugin's config.
    usage: /money <add | sub | set | ranking | give> [amount]
  apireload:
    description: Reloads the plugin's config.
    usage: /apireload